Network stats updates
Holo-Host/match-service-api-rust pull request #4
Opened 2021-10-25 16:06 UTC by alastairong

- Show "last known" info for holoports
- Add a /registered endpoint to get a list of all HPs that are in the system so we know about ones that have never been online since we started checking

2021-10-27 08:59 UTC, peeech commented on src/db.rs
> +        return Ok(Some(host));
In rust the line in function without semi-colon at the end of the line (typically the last in block) is the return value of the function. Therefore using `return` keyword here is obsolete.
```suggestion
        Ok(Some(host))
```

2021-10-27 09:00 UTC, peeech commented on src/db.rs
> +    return cursor_extended.try_collect().await.map_err(Debug);
```suggestion
   cursor_extended.try_collect().await.map_err(Debug)
```

2021-10-27 09:00 UTC, peeech commented on src/db.rs
> +    .map_err(Debug);
```suggestion
    hp_status.distinct("name", None, None)
    .await
    .map_err(Debug)
```

2021-10-27 09:02 UTC, peeech requested changes
A few comments re: syntax. Also running `cargo fmt` will make code more readable and will make sure we adhere to formatting standards.

2021-10-27 09:06 UTC, peeech commented on src/db.rs
> +                "_id": "$name",
Plus - why do we want to rename `name` field into `_id`? Underscore is signaling that property is internal in given scope.

2021-10-27 09:21 UTC, alastairong commented on src/db.rs
> +                "_id": "$name",
@peeech its how aggregation pipelines work in mongodb. The field called _id is the field used for grouping. No way around it

2021-10-27 09:29 UTC, peeech commented on src/db.rs
> +                "_id": "$name",
ok, so for internal use in struct it is the way the `_id` has to be. What we can do though is serialize this field into `id` with help of `#[serde(rename = "id")]`. See comment below.

2021-10-27 09:30 UTC, peeech commented on src/types.rs
> +    #[serde(rename = "_id")]
```suggestion
    #[serde(rename = "id")]
```

2021-10-27 09:31 UTC, peeech commented on src/db.rs
> +                "_id": "$name",
That way externally (in API response) the field name will be `id`

2021-10-27 10:27 UTC, alastairong commented on src/db.rs
> +                "_id": "$name",
I think I had to force it to not rename because otherwise I was getting Bson deserialisation errors

2021-10-27 10:27 UTC, alastairong commented on src/types.rs
> +    #[serde(rename = "_id")]
I had to intentionally set it as `_id` to prevent bson deserialisation errors.

2021-10-27 12:14 UTC, peeech commented on src/types.rs
> +    #[serde(rename = "_id")]
Sorry you're right, it goes the other way. Here the line needs to read `#[serde(rename = "_id")]` because it is an entry type from mongodb call that is deserialized into HostSummary type. For renaming to happen during serialization (while returning API call result) we would need to create a separate ReturnHostSummary type with serde rename encoded there. It might not be worth an effort though :-)

2021-10-27 12:52 UTC, alastairong commented on src/db.rs
> +                "_id": "$name",
I think we can close this comment?

2021-11-13 15:17 UTC, peeech approved these changes
I am considering this part of work done. If there's any other scope of work that needs to be added it can happen in a separate PR

2021-11-13 15:17 UTC, merged